### ISSUE TITLE
dependency "sklearn" should be "scikit-learn"

### ISSUE THREAD

**Issue by tfriedel** [libffcv/ffcv#169] opened 2022-02-20 11:49 UTC
https://github.com/libffcv/ffcv/blob/89dc2fabd59f85aab5826b294bc0d34eb236cea4/setup.py#L55

simply replace it. sklearn does install some package, but not the one we want.

**Comment by andrewilyas** [comment] 2022-02-20 16:01
From what I can tell, we actually don't use scikit-learn anywhere, so it might be safe to just delete this line?

**Comment by andrewilyas** [comment] 2022-02-20 16:01
Closing as a duplicate of #159

**Closed by andrewilyas** 2022-02-20 16:01 UTC
